---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
      fabric8.io/git-commit: "ae4c878ca3e1b27a60640c78e5038fdd97f705f5"
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-branch: "main"
    labels:
      expose: "true"
      provider: "fabric8"
      project: "oracle-jdbc-connecgtion-tester"
      version: "1.0"
      group: "com.pccw"
    name: "oracle-jdbc-connecgtion-"
  spec:
    ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "oracle-jdbc-connecgtion-tester"
      provider: "fabric8"
      group: "com.pccw"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "DeploymentConfig"
  metadata:
    annotations:
      fabric8.io/git-commit: "ae4c878ca3e1b27a60640c78e5038fdd97f705f5"
      fabric8.io/iconUrl: "img/icons/spring-boot.svg"
      fabric8.io/git-branch: "main"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=oracle-jdbc-connecgtion-tester&var-version=1.0"
    labels:
      provider: "fabric8"
      project: "oracle-jdbc-connecgtion-tester"
      version: "1.0"
      group: "com.pccw"
    name: "oracle-jdbc-connecgtion-"
  spec:
    replicas: 1
    selector:
      project: "oracle-jdbc-connecgtion-tester"
      provider: "fabric8"
      group: "com.pccw"
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: "Rolling"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "ae4c878ca3e1b27a60640c78e5038fdd97f705f5"
          fabric8.io/iconUrl: "img/icons/spring-boot.svg"
          fabric8.io/git-branch: "main"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=oracle-jdbc-connecgtion-tester&var-version=1.0"
        labels:
          provider: "fabric8"
          project: "oracle-jdbc-connecgtion-tester"
          version: "1.0"
          group: "com.pccw"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "pccw/oracle-jdbc-connecgtion-tester:1.0"
          imagePullPolicy: "IfNotPresent"
          name: "spring-boot"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          - containerPort: 9779
            name: "prometheus"
            protocol: "TCP"
          - containerPort: 8778
            name: "jolokia"
            protocol: "TCP"
          securityContext:
            privileged: false
    triggers:
    - type: "ConfigChange"
